/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";

import { apiClient } from "../axios/orvalMutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 본인 결제 내역 조회
 */
export const getGetMyPaymentsUrl = () => {
	return `/v1/payments`;
};

export const getMyPayments = async (options?: RequestInit): Promise<Blob> => {
	return apiClient<Blob>(getGetMyPaymentsUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetMyPaymentsInfiniteQueryKey = () => {
	return ["infinite", `/v1/payments`] as const;
};

export const getGetMyPaymentsQueryKey = () => {
	return [`/v1/payments`] as const;
};

export const getGetMyPaymentsInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getMyPayments>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getMyPayments>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMyPaymentsInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyPayments>>> = ({
		signal,
	}) => getMyPayments({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMyPayments>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyPaymentsInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMyPayments>>
>;
export type GetMyPaymentsInfiniteQueryError = Blob;

export function useGetMyPaymentsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMyPayments>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMyPayments>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMyPayments>>,
					TError,
					Awaited<ReturnType<typeof getMyPayments>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPaymentsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMyPayments>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMyPayments>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMyPayments>>,
					TError,
					Awaited<ReturnType<typeof getMyPayments>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPaymentsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMyPayments>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMyPayments>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 본인 결제 내역 조회
 */

export function useGetMyPaymentsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMyPayments>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMyPayments>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMyPaymentsInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMyPaymentsQueryOptions = <
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getMyPayments>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMyPaymentsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyPayments>>> = ({
		signal,
	}) => getMyPayments({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getMyPayments>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyPaymentsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMyPayments>>
>;
export type GetMyPaymentsQueryError = Blob;

export function useGetMyPayments<
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMyPayments>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMyPayments>>,
					TError,
					Awaited<ReturnType<typeof getMyPayments>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPayments<
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMyPayments>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMyPayments>>,
					TError,
					Awaited<ReturnType<typeof getMyPayments>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPayments<
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMyPayments>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 본인 결제 내역 조회
 */

export function useGetMyPayments<
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMyPayments>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMyPaymentsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMyPaymentsSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof getMyPayments>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMyPaymentsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyPayments>>> = ({
		signal,
	}) => getMyPayments({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getMyPayments>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyPaymentsSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMyPayments>>
>;
export type GetMyPaymentsSuspenseQueryError = Blob;

export function useGetMyPaymentsSuspense<
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMyPayments>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPaymentsSuspense<
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMyPayments>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPaymentsSuspense<
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMyPayments>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 본인 결제 내역 조회
 */

export function useGetMyPaymentsSuspense<
	TData = Awaited<ReturnType<typeof getMyPayments>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMyPayments>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMyPaymentsSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
