/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";

import { apiClient } from "../axios/orvalMutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 특정 설문의 응답 데이터를 CSV 파일로 내보냅니다.
 */
export const getExportUrl = (surveyId: number) => {
	return `/v1/surveys/${surveyId}/export`;
};

export const _export = async (
	surveyId: number,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getExportUrl(surveyId), {
		...options,
		method: "GET",
	});
};

export const getExportInfiniteQueryKey = (surveyId: number) => {
	return ["infinite", `/v1/surveys/${surveyId}/export`] as const;
};

export const getExportQueryKey = (surveyId: number) => {
	return [`/v1/surveys/${surveyId}/export`] as const;
};

export const getExportInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof _export>>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getExportInfiniteQueryKey(surveyId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof _export>>> = ({
		signal,
	}) => _export(surveyId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!surveyId,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof _export>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type _ExportInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof _export>>
>;
export type _ExportInfiniteQueryError = Blob;

export function useExportInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof _export>>>,
	TError = Blob,
>(
	surveyId: number,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof _export>>,
					TError,
					Awaited<ReturnType<typeof _export>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof _export>>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof _export>>,
					TError,
					Awaited<ReturnType<typeof _export>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof _export>>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 특정 설문의 응답 데이터를 CSV 파일로 내보냅니다.
 */

export function useExportInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof _export>>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getExportInfiniteQueryOptions(surveyId, options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getExportQueryOptions = <
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getExportQueryKey(surveyId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof _export>>> = ({
		signal,
	}) => _export(surveyId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!surveyId,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type _ExportQueryResult = NonNullable<
	Awaited<ReturnType<typeof _export>>
>;
export type _ExportQueryError = Blob;

export function useExport<
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof _export>>,
					TError,
					Awaited<ReturnType<typeof _export>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExport<
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof _export>>,
					TError,
					Awaited<ReturnType<typeof _export>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExport<
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 특정 설문의 응답 데이터를 CSV 파일로 내보냅니다.
 */

export function useExport<
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof _export>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getExportQueryOptions(surveyId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getExportSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getExportQueryKey(surveyId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof _export>>> = ({
		signal,
	}) => _export(surveyId, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof _export>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type _ExportSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof _export>>
>;
export type _ExportSuspenseQueryError = Blob;

export function useExportSuspense<
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportSuspense<
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportSuspense<
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 특정 설문의 응답 데이터를 CSV 파일로 내보냅니다.
 */

export function useExportSuspense<
	TData = Awaited<ReturnType<typeof _export>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof _export>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getExportSuspenseQueryOptions(surveyId, options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
