/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useMutation,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";
import { apiClient } from "../axios/orvalMutator";
import type { OnboardingRequest, ProfileImageUpdateRequest } from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 프로필 이미지 URL을 설정합니다.
 * @summary 프로필 이미지 설정
 */
export const getChangeProfileImageUrl = () => {
	return `/v1/members/profile-image`;
};

export const changeProfileImage = async (
	profileImageUpdateRequest: ProfileImageUpdateRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getChangeProfileImageUrl(), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(profileImageUpdateRequest),
	});
};

export const getChangeProfileImageMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof changeProfileImage>>,
		TError,
		{ data: ProfileImageUpdateRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof changeProfileImage>>,
	TError,
	{ data: ProfileImageUpdateRequest },
	TContext
> => {
	const mutationKey = ["changeProfileImage"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof changeProfileImage>>,
		{ data: ProfileImageUpdateRequest }
	> = (props) => {
		const { data } = props ?? {};

		return changeProfileImage(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ChangeProfileImageMutationResult = NonNullable<
	Awaited<ReturnType<typeof changeProfileImage>>
>;
export type ChangeProfileImageMutationBody = ProfileImageUpdateRequest;
export type ChangeProfileImageMutationError = Blob;

/**
 * @summary 프로필 이미지 설정
 */
export const useChangeProfileImage = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof changeProfileImage>>,
			TError,
			{ data: ProfileImageUpdateRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof changeProfileImage>>,
	TError,
	{ data: ProfileImageUpdateRequest },
	TContext
> => {
	return useMutation(
		getChangeProfileImageMutationOptions(options),
		queryClient,
	);
};
/**
 * 거주지와 관심사를 등록하고 온보딩을 완료합니다.
 * @summary 온보딩 정보 설정
 */
export const getCompleteOnboardingUrl = () => {
	return `/v1/members/onboarding`;
};

export const completeOnboarding = async (
	onboardingRequest: OnboardingRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getCompleteOnboardingUrl(), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(onboardingRequest),
	});
};

export const getCompleteOnboardingMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof completeOnboarding>>,
		TError,
		{ data: OnboardingRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof completeOnboarding>>,
	TError,
	{ data: OnboardingRequest },
	TContext
> => {
	const mutationKey = ["completeOnboarding"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof completeOnboarding>>,
		{ data: OnboardingRequest }
	> = (props) => {
		const { data } = props ?? {};

		return completeOnboarding(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CompleteOnboardingMutationResult = NonNullable<
	Awaited<ReturnType<typeof completeOnboarding>>
>;
export type CompleteOnboardingMutationBody = OnboardingRequest;
export type CompleteOnboardingMutationError = Blob;

/**
 * @summary 온보딩 정보 설정
 */
export const useCompleteOnboarding = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof completeOnboarding>>,
			TError,
			{ data: OnboardingRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof completeOnboarding>>,
	TError,
	{ data: OnboardingRequest },
	TContext
> => {
	return useMutation(
		getCompleteOnboardingMutationOptions(options),
		queryClient,
	);
};
/**
 * 현재 로그인한 회원의 정보(이름, 프로필 URL, 보유 코인 수)를 조회합니다.
 * @summary 회원 정보를 조회합니다.
 */
export const getGetMemberInfoUrl = () => {
	return `/v1/members`;
};

export const getMemberInfo = async (options?: RequestInit): Promise<Blob> => {
	return apiClient<Blob>(getGetMemberInfoUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetMemberInfoInfiniteQueryKey = () => {
	return ["infinite", `/v1/members`] as const;
};

export const getGetMemberInfoQueryKey = () => {
	return [`/v1/members`] as const;
};

export const getGetMemberInfoInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getMemberInfo>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getMemberInfo>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMemberInfoInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMemberInfo>>> = ({
		signal,
	}) => getMemberInfo({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMemberInfo>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMemberInfoInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMemberInfo>>
>;
export type GetMemberInfoInfiniteQueryError = Blob;

export function useGetMemberInfoInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMemberInfo>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMemberInfo>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMemberInfo>>,
					TError,
					Awaited<ReturnType<typeof getMemberInfo>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMemberInfoInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMemberInfo>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMemberInfo>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMemberInfo>>,
					TError,
					Awaited<ReturnType<typeof getMemberInfo>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMemberInfoInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMemberInfo>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMemberInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 회원 정보를 조회합니다.
 */

export function useGetMemberInfoInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMemberInfo>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMemberInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMemberInfoInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMemberInfoQueryOptions = <
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getMemberInfo>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMemberInfoQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMemberInfo>>> = ({
		signal,
	}) => getMemberInfo({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getMemberInfo>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMemberInfoQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMemberInfo>>
>;
export type GetMemberInfoQueryError = Blob;

export function useGetMemberInfo<
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMemberInfo>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMemberInfo>>,
					TError,
					Awaited<ReturnType<typeof getMemberInfo>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMemberInfo<
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMemberInfo>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMemberInfo>>,
					TError,
					Awaited<ReturnType<typeof getMemberInfo>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMemberInfo<
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMemberInfo>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 회원 정보를 조회합니다.
 */

export function useGetMemberInfo<
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMemberInfo>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMemberInfoQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMemberInfoSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof getMemberInfo>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMemberInfoQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMemberInfo>>> = ({
		signal,
	}) => getMemberInfo({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getMemberInfo>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMemberInfoSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMemberInfo>>
>;
export type GetMemberInfoSuspenseQueryError = Blob;

export function useGetMemberInfoSuspense<
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMemberInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMemberInfoSuspense<
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMemberInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMemberInfoSuspense<
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMemberInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 회원 정보를 조회합니다.
 */

export function useGetMemberInfoSuspense<
	TData = Awaited<ReturnType<typeof getMemberInfo>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMemberInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMemberInfoSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
