/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export interface FormRequestResponse {
	id?: number;
	formLink?: string;
	questionCount?: number;
	targetResponseCount?: number;
	deadline?: string;
	requesterEmail?: string;
	price?: number;
	isRegistered?: boolean;
	registeredSurveyId?: number;
	createdAt?: string;
}
