/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export interface GlobalStatsResponse {
	totalDueCount?: number;
	totalCompletedCount?: number;
	totalPromotionCount?: number;
	dailyUserCount?: number;
}
