/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export interface ParameterData {
	/** 오류가 발생한 필드 */
	key?: string;
	/** 넣은 요청값 */
	value?: string;
	/** 오류 발생 이유 */
	reason?: string;
}
