/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export interface ProfileImageUpdateRequest {
	/** 프로필 이미지 URL (null 가능) */
	profileUrl?: string;
}
