/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export type SurveyFormRequestAgesItem =
	(typeof SurveyFormRequestAgesItem)[keyof typeof SurveyFormRequestAgesItem];

export const SurveyFormRequestAgesItem = {
	ALL: "ALL",
	TEN: "TEN",
	TWENTY: "TWENTY",
	THIRTY: "THIRTY",
	FOURTY: "FOURTY",
	FIFTY: "FIFTY",
	SIXTY: "SIXTY",
	OVER: "OVER",
} as const;
