/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { SurveyDetailResponseStatus } from "./surveyDetailResponseStatus";
import type { SurveyInfoResponse } from "./surveyInfoResponse";

export interface SurveyDetailResponse {
	surveyId?: number;
	title?: string;
	status?: SurveyDetailResponseStatus;
	totalCoin?: number;
	createdAt?: string;
	deadline?: string;
	surveyInfo?: SurveyInfoResponse;
}
