/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { OptionDto } from "./optionDto";
import type { UpsertInfoQuestionType } from "./upsertInfoQuestionType";

export interface UpsertInfo {
	questionId?: number;
	title?: string;
	description?: string;
	isRequired?: boolean;
	questionType?: UpsertInfoQuestionType;
	questionOrder?: number;
	maxChoice?: number;
	hasNoneOption?: boolean;
	hasCustomInput?: boolean;
	options?: OptionDto[];
	minValue?: string;
	maxValue?: string;
	rate?: number;
	defaultDate?: string;
}
