/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { apiClient } from "../axios/orvalMutator";
import type {
	PromotionIssueRequest,
	PromotionRecheckPendingRequest,
} from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * PENDING 상태로 남아있는 프로모션들을 재조회하여 최신 상태로 갱신합니다.
 * @summary [호출 유의] PENDING 프로모션 재조회
 */
export const getRecheckPendingUrl = () => {
	return `/toss/promotion/recheck-pending`;
};

export const recheckPending = async (
	promotionRecheckPendingRequest: PromotionRecheckPendingRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getRecheckPendingUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(promotionRecheckPendingRequest),
	});
};

export const getRecheckPendingMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof recheckPending>>,
		TError,
		{ data: PromotionRecheckPendingRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof recheckPending>>,
	TError,
	{ data: PromotionRecheckPendingRequest },
	TContext
> => {
	const mutationKey = ["recheckPending"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof recheckPending>>,
		{ data: PromotionRecheckPendingRequest }
	> = (props) => {
		const { data } = props ?? {};

		return recheckPending(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RecheckPendingMutationResult = NonNullable<
	Awaited<ReturnType<typeof recheckPending>>
>;
export type RecheckPendingMutationBody = PromotionRecheckPendingRequest;
export type RecheckPendingMutationError = Blob;

/**
 * @summary [호출 유의] PENDING 프로모션 재조회
 */
export const useRecheckPending = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof recheckPending>>,
			TError,
			{ data: PromotionRecheckPendingRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof recheckPending>>,
	TError,
	{ data: PromotionRecheckPendingRequest },
	TContext
> => {
	return useMutation(getRecheckPendingMutationOptions(options), queryClient);
};
/**
 * 프로모션 코드/금액으로 토스 포인트 지급을 실행합니다.
 * @summary 토스포인트 지급 실행
 */
export const getIssueUrl = () => {
	return `/toss/promotion/issue`;
};

export const issue = async (
	promotionIssueRequest: PromotionIssueRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getIssueUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(promotionIssueRequest),
	});
};

export const getIssueMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof issue>>,
		TError,
		{ data: PromotionIssueRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof issue>>,
	TError,
	{ data: PromotionIssueRequest },
	TContext
> => {
	const mutationKey = ["issue"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof issue>>,
		{ data: PromotionIssueRequest }
	> = (props) => {
		const { data } = props ?? {};

		return issue(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type IssueMutationResult = NonNullable<
	Awaited<ReturnType<typeof issue>>
>;
export type IssueMutationBody = PromotionIssueRequest;
export type IssueMutationError = Blob;

/**
 * @summary 토스포인트 지급 실행
 */
export const useIssue = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof issue>>,
			TError,
			{ data: PromotionIssueRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof issue>>,
	TError,
	{ data: PromotionIssueRequest },
	TContext
> => {
	return useMutation(getIssueMutationOptions(options), queryClient);
};
