/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { apiClient } from "../axios/orvalMutator";
import type { UploadBody } from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 이미지 업로드 후 Public URL을 반환합니다. URL은 이후 게시글 엔티티의 POST 요청에서 image_url 필드로 저장합니다.
 * @summary 이미지 업로드
 */
export const getUploadUrl = () => {
	return `/v1/images`;
};

export const upload = async (
	uploadBody: UploadBody,
	options?: RequestInit,
): Promise<Blob> => {
	const formData = new FormData();
	formData.append(`file`, uploadBody.file);

	return apiClient<Blob>(getUploadUrl(), {
		...options,
		method: "POST",
		body: formData,
	});
};

export const getUploadMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof upload>>,
		TError,
		{ data: UploadBody },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof upload>>,
	TError,
	{ data: UploadBody },
	TContext
> => {
	const mutationKey = ["upload"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof upload>>,
		{ data: UploadBody }
	> = (props) => {
		const { data } = props ?? {};

		return upload(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UploadMutationResult = NonNullable<
	Awaited<ReturnType<typeof upload>>
>;
export type UploadMutationBody = UploadBody;
export type UploadMutationError = Blob;

/**
 * @summary 이미지 업로드
 */
export const useUpload = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof upload>>,
			TError,
			{ data: UploadBody },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof upload>>,
	TError,
	{ data: UploadBody },
	TContext
> => {
	return useMutation(getUploadMutationOptions(options), queryClient);
};
