/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { apiClient } from "../axios/orvalMutator";
import type {
	FreeSurveyFormRequest,
	QuestionRequest,
	ScreeningRequest,
	SurveyFormCreateRequest,
	SurveyFormRequest,
	SurveyInterestRequest,
} from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 기존 문항을 수정합니다. (임시저장)
 */
export const getUpdateSurveyUrl = (surveyId: number) => {
	return `/v1/survey-form/surveys/${surveyId}/questions`;
};

export const updateSurvey = async (
	surveyId: number,
	questionRequest: QuestionRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getUpdateSurveyUrl(surveyId), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(questionRequest),
	});
};

export const getUpdateSurveyMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateSurvey>>,
		TError,
		{ surveyId: number; data: QuestionRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateSurvey>>,
	TError,
	{ surveyId: number; data: QuestionRequest },
	TContext
> => {
	const mutationKey = ["updateSurvey"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateSurvey>>,
		{ surveyId: number; data: QuestionRequest }
	> = (props) => {
		const { surveyId, data } = props ?? {};

		return updateSurvey(surveyId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateSurveyMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateSurvey>>
>;
export type UpdateSurveyMutationBody = QuestionRequest;
export type UpdateSurveyMutationError = Blob;

/**
 * @summary 기존 문항을 수정합니다. (임시저장)
 */
export const useUpdateSurvey = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateSurvey>>,
			TError,
			{ surveyId: number; data: QuestionRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateSurvey>>,
	TError,
	{ surveyId: number; data: QuestionRequest },
	TContext
> => {
	return useMutation(getUpdateSurveyMutationOptions(options), queryClient);
};
/**
 * @summary 새로운 문항을 생성합니다.
 */
export const getCreateQuestionUrl = (surveyId: number) => {
	return `/v1/survey-form/surveys/${surveyId}/questions`;
};

export const createQuestion = async (
	surveyId: number,
	questionRequest: QuestionRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getCreateQuestionUrl(surveyId), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(questionRequest),
	});
};

export const getCreateQuestionMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createQuestion>>,
		TError,
		{ surveyId: number; data: QuestionRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createQuestion>>,
	TError,
	{ surveyId: number; data: QuestionRequest },
	TContext
> => {
	const mutationKey = ["createQuestion"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createQuestion>>,
		{ surveyId: number; data: QuestionRequest }
	> = (props) => {
		const { surveyId, data } = props ?? {};

		return createQuestion(surveyId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateQuestionMutationResult = NonNullable<
	Awaited<ReturnType<typeof createQuestion>>
>;
export type CreateQuestionMutationBody = QuestionRequest;
export type CreateQuestionMutationError = Blob;

/**
 * @summary 새로운 문항을 생성합니다.
 */
export const useCreateQuestion = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createQuestion>>,
			TError,
			{ surveyId: number; data: QuestionRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createQuestion>>,
	TError,
	{ surveyId: number; data: QuestionRequest },
	TContext
> => {
	return useMutation(getCreateQuestionMutationOptions(options), queryClient);
};
/**
 * @summary 설문 폼을 생성합니다.
 */
export const getCreateSurveyUrl = () => {
	return `/v1/survey-form/surveys`;
};

export const createSurvey = async (
	surveyFormCreateRequest: SurveyFormCreateRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getCreateSurveyUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(surveyFormCreateRequest),
	});
};

export const getCreateSurveyMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createSurvey>>,
		TError,
		{ data: SurveyFormCreateRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createSurvey>>,
	TError,
	{ data: SurveyFormCreateRequest },
	TContext
> => {
	const mutationKey = ["createSurvey"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createSurvey>>,
		{ data: SurveyFormCreateRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createSurvey(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateSurveyMutationResult = NonNullable<
	Awaited<ReturnType<typeof createSurvey>>
>;
export type CreateSurveyMutationBody = SurveyFormCreateRequest;
export type CreateSurveyMutationError = Blob;

/**
 * @summary 설문 폼을 생성합니다.
 */
export const useCreateSurvey = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createSurvey>>,
			TError,
			{ data: SurveyFormCreateRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createSurvey>>,
	TError,
	{ data: SurveyFormCreateRequest },
	TContext
> => {
	return useMutation(getCreateSurveyMutationOptions(options), queryClient);
};
/**
 * @summary 설문에 대한 스크리닝 문항을 생성합니다.
 */
export const getCreateScreeningUrl = (surveyId: number) => {
	return `/v1/survey-form/surveys/${surveyId}/screenings`;
};

export const createScreening = async (
	surveyId: number,
	screeningRequest: ScreeningRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getCreateScreeningUrl(surveyId), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(screeningRequest),
	});
};

export const getCreateScreeningMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createScreening>>,
		TError,
		{ surveyId: number; data: ScreeningRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createScreening>>,
	TError,
	{ surveyId: number; data: ScreeningRequest },
	TContext
> => {
	const mutationKey = ["createScreening"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createScreening>>,
		{ surveyId: number; data: ScreeningRequest }
	> = (props) => {
		const { surveyId, data } = props ?? {};

		return createScreening(surveyId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateScreeningMutationResult = NonNullable<
	Awaited<ReturnType<typeof createScreening>>
>;
export type CreateScreeningMutationBody = ScreeningRequest;
export type CreateScreeningMutationError = Blob;

/**
 * @summary 설문에 대한 스크리닝 문항을 생성합니다.
 */
export const useCreateScreening = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createScreening>>,
			TError,
			{ surveyId: number; data: ScreeningRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createScreening>>,
	TError,
	{ surveyId: number; data: ScreeningRequest },
	TContext
> => {
	return useMutation(getCreateScreeningMutationOptions(options), queryClient);
};
/**
 * @summary 폼을 완성합니다.
 */
export const getCompleteSurvey1Url = (surveyId: number) => {
	return `/v1/survey-form/surveys/${surveyId}`;
};

export const completeSurvey1 = async (
	surveyId: number,
	surveyFormRequest: SurveyFormRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getCompleteSurvey1Url(surveyId), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(surveyFormRequest),
	});
};

export const getCompleteSurvey1MutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof completeSurvey1>>,
		TError,
		{ surveyId: number; data: SurveyFormRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof completeSurvey1>>,
	TError,
	{ surveyId: number; data: SurveyFormRequest },
	TContext
> => {
	const mutationKey = ["completeSurvey1"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof completeSurvey1>>,
		{ surveyId: number; data: SurveyFormRequest }
	> = (props) => {
		const { surveyId, data } = props ?? {};

		return completeSurvey1(surveyId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CompleteSurvey1MutationResult = NonNullable<
	Awaited<ReturnType<typeof completeSurvey1>>
>;
export type CompleteSurvey1MutationBody = SurveyFormRequest;
export type CompleteSurvey1MutationError = Blob;

/**
 * @summary 폼을 완성합니다.
 */
export const useCompleteSurvey1 = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof completeSurvey1>>,
			TError,
			{ surveyId: number; data: SurveyFormRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof completeSurvey1>>,
	TError,
	{ surveyId: number; data: SurveyFormRequest },
	TContext
> => {
	return useMutation(getCompleteSurvey1MutationOptions(options), queryClient);
};
/**
 * @summary 설문의 관심사를 등록합니다.
 */
export const getUpdateInterestUrl = (surveyId: number) => {
	return `/v1/survey-form/surveys/${surveyId}/interests`;
};

export const updateInterest = async (
	surveyId: number,
	surveyInterestRequest: SurveyInterestRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getUpdateInterestUrl(surveyId), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(surveyInterestRequest),
	});
};

export const getUpdateInterestMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateInterest>>,
		TError,
		{ surveyId: number; data: SurveyInterestRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateInterest>>,
	TError,
	{ surveyId: number; data: SurveyInterestRequest },
	TContext
> => {
	const mutationKey = ["updateInterest"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateInterest>>,
		{ surveyId: number; data: SurveyInterestRequest }
	> = (props) => {
		const { surveyId, data } = props ?? {};

		return updateInterest(surveyId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateInterestMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateInterest>>
>;
export type UpdateInterestMutationBody = SurveyInterestRequest;
export type UpdateInterestMutationError = Blob;

/**
 * @summary 설문의 관심사를 등록합니다.
 */
export const useUpdateInterest = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateInterest>>,
			TError,
			{ surveyId: number; data: SurveyInterestRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateInterest>>,
	TError,
	{ surveyId: number; data: SurveyInterestRequest },
	TContext
> => {
	return useMutation(getUpdateInterestMutationOptions(options), queryClient);
};
/**
 * @summary 무료 설문 폼을 완성합니다.
 */
export const getCompleteFreeSurveyUrl = (surveyId: number) => {
	return `/v1/survey-form/surveys/${surveyId}/free`;
};

export const completeFreeSurvey = async (
	surveyId: number,
	freeSurveyFormRequest: FreeSurveyFormRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getCompleteFreeSurveyUrl(surveyId), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(freeSurveyFormRequest),
	});
};

export const getCompleteFreeSurveyMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof completeFreeSurvey>>,
		TError,
		{ surveyId: number; data: FreeSurveyFormRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof completeFreeSurvey>>,
	TError,
	{ surveyId: number; data: FreeSurveyFormRequest },
	TContext
> => {
	const mutationKey = ["completeFreeSurvey"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof completeFreeSurvey>>,
		{ surveyId: number; data: FreeSurveyFormRequest }
	> = (props) => {
		const { surveyId, data } = props ?? {};

		return completeFreeSurvey(surveyId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CompleteFreeSurveyMutationResult = NonNullable<
	Awaited<ReturnType<typeof completeFreeSurvey>>
>;
export type CompleteFreeSurveyMutationBody = FreeSurveyFormRequest;
export type CompleteFreeSurveyMutationError = Blob;

/**
 * @summary 무료 설문 폼을 완성합니다.
 */
export const useCompleteFreeSurvey = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof completeFreeSurvey>>,
			TError,
			{ surveyId: number; data: FreeSurveyFormRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof completeFreeSurvey>>,
	TError,
	{ surveyId: number; data: FreeSurveyFormRequest },
	TContext
> => {
	return useMutation(
		getCompleteFreeSurveyMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary 설문 제목과 상세설명을 수정합니다.
 */
export const getUpdateSurvey1Url = (surveyId: number) => {
	return `/v1/survey-form/surveys/${surveyId}/display`;
};

export const updateSurvey1 = async (
	surveyId: number,
	surveyFormCreateRequest: SurveyFormCreateRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getUpdateSurvey1Url(surveyId), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(surveyFormCreateRequest),
	});
};

export const getUpdateSurvey1MutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateSurvey1>>,
		TError,
		{ surveyId: number; data: SurveyFormCreateRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateSurvey1>>,
	TError,
	{ surveyId: number; data: SurveyFormCreateRequest },
	TContext
> => {
	const mutationKey = ["updateSurvey1"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateSurvey1>>,
		{ surveyId: number; data: SurveyFormCreateRequest }
	> = (props) => {
		const { surveyId, data } = props ?? {};

		return updateSurvey1(surveyId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateSurvey1MutationResult = NonNullable<
	Awaited<ReturnType<typeof updateSurvey1>>
>;
export type UpdateSurvey1MutationBody = SurveyFormCreateRequest;
export type UpdateSurvey1MutationError = Blob;

/**
 * @summary 설문 제목과 상세설명을 수정합니다.
 */
export const useUpdateSurvey1 = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateSurvey1>>,
			TError,
			{ surveyId: number; data: SurveyFormCreateRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateSurvey1>>,
	TError,
	{ surveyId: number; data: SurveyFormCreateRequest },
	TContext
> => {
	return useMutation(getUpdateSurvey1MutationOptions(options), queryClient);
};
