/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { apiClient } from "../../service/axios/orvalMutator";
import type { TossLoginRequest, TossReissueRequest } from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 인가코드와 referrer을 받아 토큰을 헤더(Authorization, X-Refresh-Token)로 전달합니다.
 * @summary 토스 로그인
 */
export const getTossLoginUrl = () => {
	return `/auth/toss/login`;
};

export const tossLogin = async (
	tossLoginRequest: TossLoginRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getTossLoginUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(tossLoginRequest),
	});
};

export const getTossLoginMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof tossLogin>>,
		TError,
		{ data: TossLoginRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof tossLogin>>,
	TError,
	{ data: TossLoginRequest },
	TContext
> => {
	const mutationKey = ["tossLogin"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof tossLogin>>,
		{ data: TossLoginRequest }
	> = (props) => {
		const { data } = props ?? {};

		return tossLogin(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type TossLoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof tossLogin>>
>;
export type TossLoginMutationBody = TossLoginRequest;
export type TossLoginMutationError = Blob;

/**
 * @summary 토스 로그인
 */
export const useTossLogin = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof tossLogin>>,
			TError,
			{ data: TossLoginRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof tossLogin>>,
	TError,
	{ data: TossLoginRequest },
	TContext
> => {
	return useMutation(getTossLoginMutationOptions(options), queryClient);
};
/**
 * Refresh Token을 받아 유효한 경우 Access Token을 재발급합니다.
 * @summary 토큰 재발급
 */
export const getReissueUrl = () => {
	return `/auth/reissue`;
};

export const reissue = async (
	tossReissueRequest: TossReissueRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getReissueUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(tossReissueRequest),
	});
};

export const getReissueMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof reissue>>,
		TError,
		{ data: TossReissueRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof reissue>>,
	TError,
	{ data: TossReissueRequest },
	TContext
> => {
	const mutationKey = ["reissue"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof reissue>>,
		{ data: TossReissueRequest }
	> = (props) => {
		const { data } = props ?? {};

		return reissue(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ReissueMutationResult = NonNullable<
	Awaited<ReturnType<typeof reissue>>
>;
export type ReissueMutationBody = TossReissueRequest;
export type ReissueMutationError = Blob;

/**
 * @summary 토큰 재발급
 */
export const useReissue = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof reissue>>,
			TError,
			{ data: TossReissueRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof reissue>>,
	TError,
	{ data: TossReissueRequest },
	TContext
> => {
	return useMutation(getReissueMutationOptions(options), queryClient);
};
/**
 * 로그아웃 처리 및 RT 삭제 및 AT를 블랙리스트에 등록합니다.
 * @summary 로그아웃
 */
export const getLogoutUrl = () => {
	return `/auth/logout`;
};

export const logout = async (options?: RequestInit): Promise<Blob> => {
	return apiClient<Blob>(getLogoutUrl(), {
		...options,
		method: "POST",
	});
};

export const getLogoutMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof logout>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof logout>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["logout"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof logout>>,
		void
	> = () => {
		return logout(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
	Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = Blob;

/**
 * @summary 로그아웃
 */
export const useLogout = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof logout>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof logout>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getLogoutMutationOptions(options), queryClient);
};
