/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useMutation,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";
import { apiClient } from "../axios/orvalMutator";
import type { FormRequestDto, MarkAsRegisteredParams } from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 폼을 등록하기 위한 신청을 생성합니다.
 * @summary 폼 등록 신청
 */
export const getCreateGoogleFormRequestUrl = () => {
	return `/v1/form-requests`;
};

export const createGoogleFormRequest = async (
	formRequestDto: FormRequestDto,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getCreateGoogleFormRequestUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(formRequestDto),
	});
};

export const getCreateGoogleFormRequestMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createGoogleFormRequest>>,
		TError,
		{ data: FormRequestDto },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createGoogleFormRequest>>,
	TError,
	{ data: FormRequestDto },
	TContext
> => {
	const mutationKey = ["createGoogleFormRequest"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createGoogleFormRequest>>,
		{ data: FormRequestDto }
	> = (props) => {
		const { data } = props ?? {};

		return createGoogleFormRequest(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateGoogleFormRequestMutationResult = NonNullable<
	Awaited<ReturnType<typeof createGoogleFormRequest>>
>;
export type CreateGoogleFormRequestMutationBody = FormRequestDto;
export type CreateGoogleFormRequestMutationError = Blob;

/**
 * @summary 폼 등록 신청
 */
export const useCreateGoogleFormRequest = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createGoogleFormRequest>>,
			TError,
			{ data: FormRequestDto },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createGoogleFormRequest>>,
	TError,
	{ data: FormRequestDto },
	TContext
> => {
	return useMutation(
		getCreateGoogleFormRequestMutationOptions(options),
		queryClient,
	);
};
/**
 * 요청한 폼을 등록합니다.
 * @summary 폼 등록 완료 처리
 */
export const getMarkAsRegisteredUrl = (
	requestId: number,
	params: MarkAsRegisteredParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/form-requests/${requestId}/register?${stringifiedParams}`
		: `/v1/form-requests/${requestId}/register`;
};

export const markAsRegistered = async (
	requestId: number,
	params: MarkAsRegisteredParams,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getMarkAsRegisteredUrl(requestId, params), {
		...options,
		method: "POST",
	});
};

export const getMarkAsRegisteredMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof markAsRegistered>>,
		TError,
		{ requestId: number; params: MarkAsRegisteredParams },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof markAsRegistered>>,
	TError,
	{ requestId: number; params: MarkAsRegisteredParams },
	TContext
> => {
	const mutationKey = ["markAsRegistered"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof markAsRegistered>>,
		{ requestId: number; params: MarkAsRegisteredParams }
	> = (props) => {
		const { requestId, params } = props ?? {};

		return markAsRegistered(requestId, params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type MarkAsRegisteredMutationResult = NonNullable<
	Awaited<ReturnType<typeof markAsRegistered>>
>;

export type MarkAsRegisteredMutationError = Blob;

/**
 * @summary 폼 등록 완료 처리
 */
export const useMarkAsRegistered = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof markAsRegistered>>,
			TError,
			{ requestId: number; params: MarkAsRegisteredParams },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof markAsRegistered>>,
	TError,
	{ requestId: number; params: MarkAsRegisteredParams },
	TContext
> => {
	return useMutation(getMarkAsRegisteredMutationOptions(options), queryClient);
};
/**
 * 아직 등록되지 않은 폼 신청 목록을 조회합니다.
 * @summary 미등록 구글 폼 목록 조회
 */
export const getGetUnregisteredRequestsUrl = () => {
	return `/v1/form-requests/unregistered`;
};

export const getUnregisteredRequests = async (
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getGetUnregisteredRequestsUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetUnregisteredRequestsInfiniteQueryKey = () => {
	return ["infinite", `/v1/form-requests/unregistered`] as const;
};

export const getGetUnregisteredRequestsQueryKey = () => {
	return [`/v1/form-requests/unregistered`] as const;
};

export const getGetUnregisteredRequestsInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getUnregisteredRequests>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getUnregisteredRequests>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUnregisteredRequestsInfiniteQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUnregisteredRequests>>
	> = ({ signal }) => getUnregisteredRequests({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getUnregisteredRequests>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUnregisteredRequestsInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUnregisteredRequests>>
>;
export type GetUnregisteredRequestsInfiniteQueryError = Blob;

export function useGetUnregisteredRequestsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUnregisteredRequests>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUnregisteredRequests>>,
					TError,
					Awaited<ReturnType<typeof getUnregisteredRequests>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUnregisteredRequestsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUnregisteredRequests>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUnregisteredRequests>>,
					TError,
					Awaited<ReturnType<typeof getUnregisteredRequests>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUnregisteredRequestsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUnregisteredRequests>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 미등록 구글 폼 목록 조회
 */

export function useGetUnregisteredRequestsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUnregisteredRequests>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUnregisteredRequestsInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetUnregisteredRequestsQueryOptions = <
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getUnregisteredRequests>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUnregisteredRequestsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUnregisteredRequests>>
	> = ({ signal }) => getUnregisteredRequests({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getUnregisteredRequests>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUnregisteredRequestsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUnregisteredRequests>>
>;
export type GetUnregisteredRequestsQueryError = Blob;

export function useGetUnregisteredRequests<
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUnregisteredRequests>>,
					TError,
					Awaited<ReturnType<typeof getUnregisteredRequests>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUnregisteredRequests<
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUnregisteredRequests>>,
					TError,
					Awaited<ReturnType<typeof getUnregisteredRequests>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUnregisteredRequests<
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 미등록 구글 폼 목록 조회
 */

export function useGetUnregisteredRequests<
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUnregisteredRequestsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetUnregisteredRequestsSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof getUnregisteredRequests>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUnregisteredRequestsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUnregisteredRequests>>
	> = ({ signal }) => getUnregisteredRequests({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getUnregisteredRequests>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUnregisteredRequestsSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUnregisteredRequests>>
>;
export type GetUnregisteredRequestsSuspenseQueryError = Blob;

export function useGetUnregisteredRequestsSuspense<
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUnregisteredRequestsSuspense<
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUnregisteredRequestsSuspense<
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 미등록 구글 폼 목록 조회
 */

export function useGetUnregisteredRequestsSuspense<
	TData = Awaited<ReturnType<typeof getUnregisteredRequests>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getUnregisteredRequests>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUnregisteredRequestsSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
