/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { DefaultQuestionDto } from "./defaultQuestionDto";
import type { OptionDto } from "./optionDto";

export type ChoiceDto = DefaultQuestionDto & {
	maxChoice?: number;
	hasNoneOption?: boolean;
	hasCustomInput?: boolean;
	options?: OptionDto[];
};
