/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export type CreateQuestionResponseType =
	(typeof CreateQuestionResponseType)[keyof typeof CreateQuestionResponseType];

export const CreateQuestionResponseType = {
	CHOICE: "CHOICE",
	RATING: "RATING",
	NPS: "NPS",
	SHORT: "SHORT",
	LONG: "LONG",
	NUMBER: "NUMBER",
	DATE: "DATE",
	TEXT: "TEXT",
} as const;
