/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { DefaultQuestionDtoQuestionType } from "./defaultQuestionDtoQuestionType";

export interface DefaultQuestionDto {
	questionId?: number;
	surveyId?: number;
	/** 문항 타입 유형 */
	questionType?: DefaultQuestionDtoQuestionType;
	title?: string;
	description?: string;
	isRequired?: boolean;
	questionOrder?: number;
}
