/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

/**
 * 문항 타입 유형
 */
export type DefaultQuestionDtoQuestionType =
	(typeof DefaultQuestionDtoQuestionType)[keyof typeof DefaultQuestionDtoQuestionType];

export const DefaultQuestionDtoQuestionType = {
	CHOICE: "CHOICE",
	RATING: "RATING",
	NPS: "NPS",
	SHORT: "SHORT",
	LONG: "LONG",
	NUMBER: "NUMBER",
	DATE: "DATE",
} as const;
