/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { ChoiceDto } from "./choiceDto";
import type { DateDto } from "./dateDto";
import type { DefaultQuestionDto } from "./defaultQuestionDto";
import type { DeprecatedQuestionResponseInterestsItem } from "./deprecatedQuestionResponseInterestsItem";
import type { RatingDto } from "./ratingDto";

export interface DeprecatedQuestionResponse {
	surveyId?: number;
	memberId?: number;
	title?: string;
	description?: string;
	isFree?: boolean;
	interests?: DeprecatedQuestionResponseInterestsItem[];
	deadline?: string;
	info?: (DefaultQuestionDto | ChoiceDto | DateDto | RatingDto)[];
	isScreenRequired?: boolean;
	isScreened?: boolean;
	isSurveyResponded?: boolean;
}
