/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { DetailInfoAnswerMap } from "./detailInfoAnswerMap";
import type { DetailInfoType } from "./detailInfoType";

export interface DetailInfo {
	questionId?: number;
	order?: number;
	type?: DetailInfoType;
	title?: string;
	description?: string;
	isRequired?: boolean;
	/** (객관식, 평가형, NPS) 선택값 별 응답 집계 */
	answerMap?: DetailInfoAnswerMap;
	/** (주관식) 응답값 */
	answerList?: string[];
}
