/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

/**
 * (객관식, 평가형, NPS) 선택값 별 응답 집계
 */
export type DetailInfoAnswerMap = { [key: string]: number };
