/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export interface ErrorResponseString {
	/** 예외 코드 */
	code?: string;
	/** 예외 메세지 */
	message?: string;
	/** 예외 참고 데이터 */
	result?: string;
	success?: boolean;
}
