/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { ChoiceDto } from "./choiceDto";
import type { DateDto } from "./dateDto";
import type { DefaultQuestionDto } from "./defaultQuestionDto";
import type { RatingDto } from "./ratingDto";
import type { ScreeningFormData } from "./screeningFormData";

export interface FormQuestionResponse {
	surveyId?: number;
	questions?: (DefaultQuestionDto | ChoiceDto | DateDto | RatingDto)[];
	screening?: ScreeningFormData;
}
