/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export interface FormRequestDto {
	/** 폼 링크 */
	formLink?: string;
	/** 질문 수 */
	questionCount?: number;
	/** 목표 응답 수 */
	targetResponseCount?: number;
	/** 마감일 */
	deadline?: string;
	/** 신청자 이메일 */
	requesterEmail?: string;
	/** 가격 */
	price?: number;
}
