/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { GetSurveyManagementDetailInfoAgesItem } from "./getSurveyManagementDetailInfoAgesItem";
import type { GetSurveyManagementDetailInfoGendersItem } from "./getSurveyManagementDetailInfoGendersItem";
import type { GetSurveyManagementDetailInfoResidencesItem } from "./getSurveyManagementDetailInfoResidencesItem";

export type GetSurveyManagementDetailInfoParams = {
	surveyId: number;
	ages?: GetSurveyManagementDetailInfoAgesItem[];
	genders?: GetSurveyManagementDetailInfoGendersItem[];
	residences?: GetSurveyManagementDetailInfoResidencesItem[];
};
