/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { OnboardingRequestInterestsItem } from "./onboardingRequestInterestsItem";
import type { OnboardingRequestResidence } from "./onboardingRequestResidence";

export interface OnboardingRequest {
	/** 거주지 정보 */
	residence?: OnboardingRequestResidence;
	/** 관심사 목록 */
	interests?: OnboardingRequestInterestsItem[];
}
