/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { ScreeningIntroData } from "./screeningIntroData";

export interface ParticipationScreeningListResponse {
	data?: ScreeningIntroData[];
	/** 다음 문항 존재 여부 */
	hasNext?: boolean;
}
