/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export type ParticipationInfoResponseInterestsItem =
	(typeof ParticipationInfoResponseInterestsItem)[keyof typeof ParticipationInfoResponseInterestsItem];

export const ParticipationInfoResponseInterestsItem = {
	CAREER: "CAREER",
	BUSINESS: "BUSINESS",
	FINANCE: "FINANCE",
	HEALTH: "HEALTH",
	CULTURE: "CULTURE",
	FASHION: "FASHION",
	SOCIETY: "SOCIETY",
	SELF_IMPROVEMENT: "SELF_IMPROVEMENT",
	DAILY_LIFE: "DAILY_LIFE",
} as const;
