/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { ParticipationInfoResponseInterestsItem } from "./participationInfoResponseInterestsItem";

export interface ParticipationInfoResponse {
	surveyId?: number;
	title?: string;
	description?: string;
	deadline?: string;
	interests?: ParticipationInfoResponseInterestsItem[];
	responseCount?: number;
	isScreenRequired?: boolean;
	isScreened?: boolean;
	isSurveyResponded?: boolean;
	isFree?: boolean;
}
