/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { ChoiceDto } from "./choiceDto";
import type { DateDto } from "./dateDto";
import type { DefaultQuestionDto } from "./defaultQuestionDto";
import type { RatingDto } from "./ratingDto";

export interface QuestionRequest {
	/** 새로운 보기는 optionId를 null로 설정 */
	questions?: (DefaultQuestionDto | ChoiceDto | DateDto | RatingDto)[];
}
