/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { SurveyManagementResponse } from "./surveyManagementResponse";

export interface SuccessResponseSurveyManagementResponse {
	/** 상태 코드 */
	code?: number;
	/** 응답 메세지 */
	message?: string;
	/** 응답 데이터 */
	result?: SurveyManagementResponse;
	success?: boolean;
}
