/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { SurveyInfoResponseAgesItem } from "./surveyInfoResponseAgesItem";
import type { SurveyInfoResponseGender } from "./surveyInfoResponseGender";
import type { SurveyInfoResponseResidence } from "./surveyInfoResponseResidence";

export interface SurveyInfoResponse {
	dueCount?: number;
	dueCountPrice?: number;
	gender?: SurveyInfoResponseGender;
	genderPrice?: number;
	ages?: SurveyInfoResponseAgesItem[];
	agePrice?: number;
	residence?: SurveyInfoResponseResidence;
	residencePrice?: number;
}
