/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { SurveyDataInterestsItem } from "./surveyDataInterestsItem";

export interface SurveyData {
	surveyId?: number;
	memberId?: number;
	title?: string;
	description?: string;
	isFree?: boolean;
	interests?: SurveyDataInterestsItem[];
	deadline?: string;
}
