/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

export type SurveyDetailResponseStatus =
	(typeof SurveyDetailResponseStatus)[keyof typeof SurveyDetailResponseStatus];

export const SurveyDetailResponseStatus = {
	ONGOING: "ONGOING",
	WRITING: "WRITING",
	CLOSED: "CLOSED",
	REFUNDED: "REFUNDED",
	REVIEW: "REVIEW",
} as const;
