/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

/**
 * 거주지
 */
export type SurveyFormRequestResidence =
	(typeof SurveyFormRequestResidence)[keyof typeof SurveyFormRequestResidence];

export const SurveyFormRequestResidence = {
	ALL: "ALL",
	GANGWON: "GANGWON",
	GYEONGGI: "GYEONGGI",
	GYEONGNAM: "GYEONGNAM",
	GYEONGBUK: "GYEONGBUK",
	GWANGJU: "GWANGJU",
	DAEGU: "DAEGU",
	DAEJEON: "DAEJEON",
	BUSAN: "BUSAN",
	SEOUL: "SEOUL",
	ULSAN: "ULSAN",
	INCHEON: "INCHEON",
	JEONNAM: "JEONNAM",
	JEONBUK: "JEONBUK",
	JEJU: "JEJU",
	CHUNGNAM: "CHUNGNAM",
	CHUNGBUK: "CHUNGBUK",
	SEJONG: "SEJONG",
} as const;
