/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { SurveyInformationStatus } from "./surveyInformationStatus";

export interface SurveyInformation {
	surveyId?: number;
	title?: string;
	description?: string;
	status?: SurveyInformationStatus;
	isFree?: boolean;
	deadLine?: string;
	dueCount?: number;
	currentCount?: number;
	createdAt?: string;
	updatedAt?: string;
}
