/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { SurveyInterestRequestInterests } from "./surveyInterestRequestInterests";

export interface SurveyInterestRequest {
	/** 관심사 목록 */
	interests?: SurveyInterestRequestInterests;
}
