/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { SurveyData } from "./surveyData";

export interface SurveyParticipationResponse {
	/** 사용자 추천 설문 */
	recommended?: SurveyData[];
	/** 마감 임박 설문 */
	impending?: SurveyData[];
	/** 사용자 추천 설문 다음 문항 존재 여부 */
	recommendedHasNext?: boolean;
	/** 마감 임박 설문 다음 문항 존재 여부 */
	impendingHasNext?: boolean;
}
