/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { SurveyFormRequestAgesItem } from "./surveyFormRequestAgesItem";
import type { SurveyFormRequestGender } from "./surveyFormRequestGender";
import type { SurveyFormRequestResidence } from "./surveyFormRequestResidence";

export interface SurveyFormRequest {
	/** 설문 마감일 */
	deadline?: string;
	/** 성별 */
	gender?: SurveyFormRequestGender;
	/** 성별 가격 */
	genderPrice?: number;
	/** 연령대 목록 */
	ages?: SurveyFormRequestAgesItem[];
	/** 연령대 가격 */
	agePrice?: number;
	/** 거주지 */
	residence?: SurveyFormRequestResidence;
	/** 거주지 가격 */
	residencePrice?: number;
	/** 응답자 수 */
	dueCount?: number;
	/** 응답자 수 가격 */
	dueCountPrice?: number;
	/** 총 코인 */
	totalCoin?: number;
}
