/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */
import type { DetailInfo } from "./detailInfo";
import type { SurveyInfoResponse } from "./surveyInfoResponse";
import type { SurveyManagementDetailResponseStatus } from "./surveyManagementDetailResponseStatus";

export interface SurveyManagementDetailResponse {
	surveyId?: number;
	memberId?: number;
	status?: SurveyManagementDetailResponseStatus;
	surveyInfo?: SurveyInfoResponse;
	currentCount?: number;
	detailInfoList?: DetailInfo[];
}
