/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";
import { apiClient } from "../../service/axios/orvalMutator";
import type { UnlinkParams } from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getUnlinkUrl = (params: UnlinkParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/connect-out?${stringifiedParams}`
		: `/connect-out`;
};

export const unlink = async (
	params: UnlinkParams,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getUnlinkUrl(params), {
		...options,
		method: "GET",
	});
};

export const getUnlinkInfiniteQueryKey = (params?: UnlinkParams) => {
	return ["infinite", `/connect-out`, ...(params ? [params] : [])] as const;
};

export const getUnlinkQueryKey = (params?: UnlinkParams) => {
	return [`/connect-out`, ...(params ? [params] : [])] as const;
};

export const getUnlinkInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof unlink>>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUnlinkInfiniteQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof unlink>>> = ({
		signal,
	}) => unlink(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof unlink>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UnlinkInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof unlink>>
>;
export type UnlinkInfiniteQueryError = Blob;

export function useUnlinkInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof unlink>>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof unlink>>,
					TError,
					Awaited<ReturnType<typeof unlink>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnlinkInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof unlink>>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof unlink>>,
					TError,
					Awaited<ReturnType<typeof unlink>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnlinkInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof unlink>>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUnlinkInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof unlink>>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getUnlinkInfiniteQueryOptions(params, options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getUnlinkQueryOptions = <
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUnlinkQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof unlink>>> = ({
		signal,
	}) => unlink(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof unlink>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UnlinkQueryResult = NonNullable<Awaited<ReturnType<typeof unlink>>>;
export type UnlinkQueryError = Blob;

export function useUnlink<
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof unlink>>,
					TError,
					Awaited<ReturnType<typeof unlink>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnlink<
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof unlink>>,
					TError,
					Awaited<ReturnType<typeof unlink>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnlink<
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUnlink<
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getUnlinkQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getUnlinkSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUnlinkQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof unlink>>> = ({
		signal,
	}) => unlink(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof unlink>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UnlinkSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof unlink>>
>;
export type UnlinkSuspenseQueryError = Blob;

export function useUnlinkSuspense<
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnlinkSuspense<
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUnlinkSuspense<
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUnlinkSuspense<
	TData = Awaited<ReturnType<typeof unlink>>,
	TError = Blob,
>(
	params: UnlinkParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof unlink>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getUnlinkSuspenseQueryOptions(params, options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
