/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";

import { apiClient } from "../axios/orvalMutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 전체 설문에 대한 총 목표 수/참여자 수/프로모션 지급자 수/일간 활성 사용자 수를 반환합니다.
 * @summary 전체 설문 전역 통계 조회
 */
export const getGetGlobalStatsUrl = () => {
	return `/v1/surveys/global-stats`;
};

export const getGlobalStats = async (options?: RequestInit): Promise<Blob> => {
	return apiClient<Blob>(getGetGlobalStatsUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetGlobalStatsInfiniteQueryKey = () => {
	return ["infinite", `/v1/surveys/global-stats`] as const;
};

export const getGetGlobalStatsQueryKey = () => {
	return [`/v1/surveys/global-stats`] as const;
};

export const getGetGlobalStatsInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getGlobalStats>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getGlobalStats>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetGlobalStatsInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalStats>>> = ({
		signal,
	}) => getGlobalStats({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getGlobalStats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGlobalStatsInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getGlobalStats>>
>;
export type GetGlobalStatsInfiniteQueryError = Blob;

export function useGetGlobalStatsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getGlobalStats>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getGlobalStats>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getGlobalStats>>,
					TError,
					Awaited<ReturnType<typeof getGlobalStats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGlobalStatsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getGlobalStats>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getGlobalStats>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getGlobalStats>>,
					TError,
					Awaited<ReturnType<typeof getGlobalStats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGlobalStatsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getGlobalStats>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getGlobalStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 전체 설문 전역 통계 조회
 */

export function useGetGlobalStatsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getGlobalStats>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getGlobalStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetGlobalStatsInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetGlobalStatsQueryOptions = <
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getGlobalStats>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetGlobalStatsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalStats>>> = ({
		signal,
	}) => getGlobalStats({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getGlobalStats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGlobalStatsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getGlobalStats>>
>;
export type GetGlobalStatsQueryError = Blob;

export function useGetGlobalStats<
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getGlobalStats>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getGlobalStats>>,
					TError,
					Awaited<ReturnType<typeof getGlobalStats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGlobalStats<
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getGlobalStats>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getGlobalStats>>,
					TError,
					Awaited<ReturnType<typeof getGlobalStats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGlobalStats<
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getGlobalStats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 전체 설문 전역 통계 조회
 */

export function useGetGlobalStats<
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getGlobalStats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetGlobalStatsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetGlobalStatsSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof getGlobalStats>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetGlobalStatsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalStats>>> = ({
		signal,
	}) => getGlobalStats({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getGlobalStats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGlobalStatsSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getGlobalStats>>
>;
export type GetGlobalStatsSuspenseQueryError = Blob;

export function useGetGlobalStatsSuspense<
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getGlobalStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGlobalStatsSuspense<
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getGlobalStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGlobalStatsSuspense<
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getGlobalStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 전체 설문 전역 통계 조회
 */

export function useGetGlobalStatsSuspense<
	TData = Awaited<ReturnType<typeof getGlobalStats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getGlobalStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetGlobalStatsSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
