/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useMutation,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";
import { apiClient } from "../../service/axios/orvalMutator";
import type {
	GetQuestionsInWritingParams,
	GetSurveyManagementDetailInfoParams,
} from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 선택한 설문의 코인 결제를 환불하고, survey의 totalCoin 만큼 코인을 돌려줍니다.
 * @summary 내 설문 결제 환불
 */
export const getRefundMySurveyUrl = (surveyId: number) => {
	return `/v1/survey-management/${surveyId}/refund`;
};

export const refundMySurvey = async (
	surveyId: number,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getRefundMySurveyUrl(surveyId), {
		...options,
		method: "POST",
	});
};

export const getRefundMySurveyMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof refundMySurvey>>,
		TError,
		{ surveyId: number },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof refundMySurvey>>,
	TError,
	{ surveyId: number },
	TContext
> => {
	const mutationKey = ["refundMySurvey"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof refundMySurvey>>,
		{ surveyId: number }
	> = (props) => {
		const { surveyId } = props ?? {};

		return refundMySurvey(surveyId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RefundMySurveyMutationResult = NonNullable<
	Awaited<ReturnType<typeof refundMySurvey>>
>;

export type RefundMySurveyMutationError = Blob;

/**
 * @summary 내 설문 결제 환불
 */
export const useRefundMySurvey = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof refundMySurvey>>,
			TError,
			{ surveyId: number },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof refundMySurvey>>,
	TError,
	{ surveyId: number },
	TContext
> => {
	return useMutation(getRefundMySurveyMutationOptions(options), queryClient);
};
/**
 * 코인으로 결제한 설문들을 노출중/환불로 구분하여 조회합니다.
 * @summary 내 설문 목록 조회
 */
export const getGetMySurveysUrl = () => {
	return `/v1/survey-management`;
};

export const getMySurveys = async (options?: RequestInit): Promise<Blob> => {
	return apiClient<Blob>(getGetMySurveysUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetMySurveysInfiniteQueryKey = () => {
	return ["infinite", `/v1/survey-management`] as const;
};

export const getGetMySurveysQueryKey = () => {
	return [`/v1/survey-management`] as const;
};

export const getGetMySurveysInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveys>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getMySurveys>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMySurveysInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMySurveys>>> = ({
		signal,
	}) => getMySurveys({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMySurveys>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMySurveysInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMySurveys>>
>;
export type GetMySurveysInfiniteQueryError = Blob;

export function useGetMySurveysInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveys>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveys>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMySurveys>>,
					TError,
					Awaited<ReturnType<typeof getMySurveys>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveysInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveys>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveys>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMySurveys>>,
					TError,
					Awaited<ReturnType<typeof getMySurveys>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveysInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveys>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveys>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 설문 목록 조회
 */

export function useGetMySurveysInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveys>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveys>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMySurveysInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMySurveysQueryOptions = <
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getMySurveys>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMySurveysQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMySurveys>>> = ({
		signal,
	}) => getMySurveys({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getMySurveys>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMySurveysQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMySurveys>>
>;
export type GetMySurveysQueryError = Blob;

export function useGetMySurveys<
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMySurveys>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMySurveys>>,
					TError,
					Awaited<ReturnType<typeof getMySurveys>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveys<
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMySurveys>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMySurveys>>,
					TError,
					Awaited<ReturnType<typeof getMySurveys>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveys<
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMySurveys>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 설문 목록 조회
 */

export function useGetMySurveys<
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMySurveys>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMySurveysQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMySurveysSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof getMySurveys>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMySurveysQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMySurveys>>> = ({
		signal,
	}) => getMySurveys({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getMySurveys>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMySurveysSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMySurveys>>
>;
export type GetMySurveysSuspenseQueryError = Blob;

export function useGetMySurveysSuspense<
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveys>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveysSuspense<
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveys>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveysSuspense<
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveys>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 설문 목록 조회
 */

export function useGetMySurveysSuspense<
	TData = Awaited<ReturnType<typeof getMySurveys>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveys>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMySurveysSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 선택한 설문의 코인 결제 및 타겟 정보를 조회합니다.
 * @summary 내 설문 결제 상세 조회
 */
export const getGetMySurveyDetailUrl = (surveyId: number) => {
	return `/v1/survey-management/${surveyId}`;
};

export const getMySurveyDetail = async (
	surveyId: number,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getGetMySurveyDetailUrl(surveyId), {
		...options,
		method: "GET",
	});
};

export const getGetMySurveyDetailInfiniteQueryKey = (surveyId: number) => {
	return ["infinite", `/v1/survey-management/${surveyId}`] as const;
};

export const getGetMySurveyDetailQueryKey = (surveyId: number) => {
	return [`/v1/survey-management/${surveyId}`] as const;
};

export const getGetMySurveyDetailInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveyDetail>>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMySurveyDetailInfiniteQueryKey(surveyId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMySurveyDetail>>
	> = ({ signal }) =>
		getMySurveyDetail(surveyId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!surveyId,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMySurveyDetail>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMySurveyDetailInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMySurveyDetail>>
>;
export type GetMySurveyDetailInfiniteQueryError = Blob;

export function useGetMySurveyDetailInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveyDetail>>>,
	TError = Blob,
>(
	surveyId: number,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMySurveyDetail>>,
					TError,
					Awaited<ReturnType<typeof getMySurveyDetail>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveyDetailInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveyDetail>>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMySurveyDetail>>,
					TError,
					Awaited<ReturnType<typeof getMySurveyDetail>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveyDetailInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveyDetail>>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 설문 결제 상세 조회
 */

export function useGetMySurveyDetailInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMySurveyDetail>>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMySurveyDetailInfiniteQueryOptions(
		surveyId,
		options,
	);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMySurveyDetailQueryOptions = <
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMySurveyDetailQueryKey(surveyId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMySurveyDetail>>
	> = ({ signal }) =>
		getMySurveyDetail(surveyId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!surveyId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getMySurveyDetail>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMySurveyDetailQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMySurveyDetail>>
>;
export type GetMySurveyDetailQueryError = Blob;

export function useGetMySurveyDetail<
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMySurveyDetail>>,
					TError,
					Awaited<ReturnType<typeof getMySurveyDetail>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveyDetail<
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMySurveyDetail>>,
					TError,
					Awaited<ReturnType<typeof getMySurveyDetail>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveyDetail<
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 설문 결제 상세 조회
 */

export function useGetMySurveyDetail<
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMySurveyDetailQueryOptions(surveyId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMySurveyDetailSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMySurveyDetailQueryKey(surveyId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMySurveyDetail>>
	> = ({ signal }) =>
		getMySurveyDetail(surveyId, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getMySurveyDetail>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMySurveyDetailSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMySurveyDetail>>
>;
export type GetMySurveyDetailSuspenseQueryError = Blob;

export function useGetMySurveyDetailSuspense<
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveyDetailSuspense<
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySurveyDetailSuspense<
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 설문 결제 상세 조회
 */

export function useGetMySurveyDetailSuspense<
	TData = Awaited<ReturnType<typeof getMySurveyDetail>>,
	TError = Blob,
>(
	surveyId: number,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getMySurveyDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMySurveyDetailSuspenseQueryOptions(
		surveyId,
		options,
	);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary 작성 중인 설문을 조회합니다.
 */
export const getGetQuestionsInWritingUrl = (
	params: GetQuestionsInWritingParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/survey-management/writing?${stringifiedParams}`
		: `/v1/survey-management/writing`;
};

export const getQuestionsInWriting = async (
	params: GetQuestionsInWritingParams,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getGetQuestionsInWritingUrl(params), {
		...options,
		method: "GET",
	});
};

export const getGetQuestionsInWritingInfiniteQueryKey = (
	params?: GetQuestionsInWritingParams,
) => {
	return [
		"infinite",
		`/v1/survey-management/writing`,
		...(params ? [params] : []),
	] as const;
};

export const getGetQuestionsInWritingQueryKey = (
	params?: GetQuestionsInWritingParams,
) => {
	return [
		`/v1/survey-management/writing`,
		...(params ? [params] : []),
	] as const;
};

export const getGetQuestionsInWritingInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getQuestionsInWriting>>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetQuestionsInWritingInfiniteQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getQuestionsInWriting>>
	> = ({ signal }) =>
		getQuestionsInWriting(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getQuestionsInWriting>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetQuestionsInWritingInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getQuestionsInWriting>>
>;
export type GetQuestionsInWritingInfiniteQueryError = Blob;

export function useGetQuestionsInWritingInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getQuestionsInWriting>>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getQuestionsInWriting>>,
					TError,
					Awaited<ReturnType<typeof getQuestionsInWriting>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuestionsInWritingInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getQuestionsInWriting>>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getQuestionsInWriting>>,
					TError,
					Awaited<ReturnType<typeof getQuestionsInWriting>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuestionsInWritingInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getQuestionsInWriting>>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 작성 중인 설문을 조회합니다.
 */

export function useGetQuestionsInWritingInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getQuestionsInWriting>>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetQuestionsInWritingInfiniteQueryOptions(
		params,
		options,
	);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetQuestionsInWritingQueryOptions = <
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetQuestionsInWritingQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getQuestionsInWriting>>
	> = ({ signal }) =>
		getQuestionsInWriting(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getQuestionsInWriting>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetQuestionsInWritingQueryResult = NonNullable<
	Awaited<ReturnType<typeof getQuestionsInWriting>>
>;
export type GetQuestionsInWritingQueryError = Blob;

export function useGetQuestionsInWriting<
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getQuestionsInWriting>>,
					TError,
					Awaited<ReturnType<typeof getQuestionsInWriting>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuestionsInWriting<
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getQuestionsInWriting>>,
					TError,
					Awaited<ReturnType<typeof getQuestionsInWriting>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuestionsInWriting<
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 작성 중인 설문을 조회합니다.
 */

export function useGetQuestionsInWriting<
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetQuestionsInWritingQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetQuestionsInWritingSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetQuestionsInWritingQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getQuestionsInWriting>>
	> = ({ signal }) =>
		getQuestionsInWriting(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getQuestionsInWriting>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetQuestionsInWritingSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getQuestionsInWriting>>
>;
export type GetQuestionsInWritingSuspenseQueryError = Blob;

export function useGetQuestionsInWritingSuspense<
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuestionsInWritingSuspense<
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuestionsInWritingSuspense<
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 작성 중인 설문을 조회합니다.
 */

export function useGetQuestionsInWritingSuspense<
	TData = Awaited<ReturnType<typeof getQuestionsInWriting>>,
	TError = Blob,
>(
	params: GetQuestionsInWritingParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getQuestionsInWriting>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetQuestionsInWritingSuspenseQueryOptions(
		params,
		options,
	);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary 사용자가 생성한 설문을 조회합니다.
 */
export const getGetSurveyManagementListUrl = () => {
	return `/v1/survey-management/surveys`;
};

export const getSurveyManagementList = async (
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getGetSurveyManagementListUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetSurveyManagementListInfiniteQueryKey = () => {
	return ["infinite", `/v1/survey-management/surveys`] as const;
};

export const getGetSurveyManagementListQueryKey = () => {
	return [`/v1/survey-management/surveys`] as const;
};

export const getGetSurveyManagementListInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getSurveyManagementList>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getSurveyManagementList>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetSurveyManagementListInfiniteQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getSurveyManagementList>>
	> = ({ signal }) => getSurveyManagementList({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getSurveyManagementList>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSurveyManagementListInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSurveyManagementList>>
>;
export type GetSurveyManagementListInfiniteQueryError = Blob;

export function useGetSurveyManagementListInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getSurveyManagementList>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSurveyManagementList>>,
					TError,
					Awaited<ReturnType<typeof getSurveyManagementList>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementListInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getSurveyManagementList>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSurveyManagementList>>,
					TError,
					Awaited<ReturnType<typeof getSurveyManagementList>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementListInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getSurveyManagementList>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자가 생성한 설문을 조회합니다.
 */

export function useGetSurveyManagementListInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getSurveyManagementList>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetSurveyManagementListInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetSurveyManagementListQueryOptions = <
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getSurveyManagementList>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetSurveyManagementListQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getSurveyManagementList>>
	> = ({ signal }) => getSurveyManagementList({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getSurveyManagementList>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSurveyManagementListQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSurveyManagementList>>
>;
export type GetSurveyManagementListQueryError = Blob;

export function useGetSurveyManagementList<
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSurveyManagementList>>,
					TError,
					Awaited<ReturnType<typeof getSurveyManagementList>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementList<
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSurveyManagementList>>,
					TError,
					Awaited<ReturnType<typeof getSurveyManagementList>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementList<
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자가 생성한 설문을 조회합니다.
 */

export function useGetSurveyManagementList<
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetSurveyManagementListQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetSurveyManagementListSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof getSurveyManagementList>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetSurveyManagementListQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getSurveyManagementList>>
	> = ({ signal }) => getSurveyManagementList({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getSurveyManagementList>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSurveyManagementListSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSurveyManagementList>>
>;
export type GetSurveyManagementListSuspenseQueryError = Blob;

export function useGetSurveyManagementListSuspense<
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementListSuspense<
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementListSuspense<
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자가 생성한 설문을 조회합니다.
 */

export function useGetSurveyManagementListSuspense<
	TData = Awaited<ReturnType<typeof getSurveyManagementList>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementList>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetSurveyManagementListSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary 사용자가 응답을 확인할 설문을 상세 조회합니다.
 */
export const getGetSurveyManagementDetailInfoUrl = (
	params: GetSurveyManagementDetailInfoParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/survey-management/surveys/answers?${stringifiedParams}`
		: `/v1/survey-management/surveys/answers`;
};

export const getSurveyManagementDetailInfo = async (
	params: GetSurveyManagementDetailInfoParams,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getGetSurveyManagementDetailInfoUrl(params), {
		...options,
		method: "GET",
	});
};

export const getGetSurveyManagementDetailInfoInfiniteQueryKey = (
	params?: GetSurveyManagementDetailInfoParams,
) => {
	return [
		"infinite",
		`/v1/survey-management/surveys/answers`,
		...(params ? [params] : []),
	] as const;
};

export const getGetSurveyManagementDetailInfoQueryKey = (
	params?: GetSurveyManagementDetailInfoParams,
) => {
	return [
		`/v1/survey-management/surveys/answers`,
		...(params ? [params] : []),
	] as const;
};

export const getGetSurveyManagementDetailInfoInfiniteQueryOptions = <
	TData = InfiniteData<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
	>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetSurveyManagementDetailInfoInfiniteQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
	> = ({ signal }) =>
		getSurveyManagementDetailInfo(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSurveyManagementDetailInfoInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
>;
export type GetSurveyManagementDetailInfoInfiniteQueryError = Blob;

export function useGetSurveyManagementDetailInfoInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
	>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
					TError,
					Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementDetailInfoInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
	>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
					TError,
					Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementDetailInfoInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
	>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자가 응답을 확인할 설문을 상세 조회합니다.
 */

export function useGetSurveyManagementDetailInfoInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
	>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetSurveyManagementDetailInfoInfiniteQueryOptions(
		params,
		options,
	);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetSurveyManagementDetailInfoQueryOptions = <
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetSurveyManagementDetailInfoQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
	> = ({ signal }) =>
		getSurveyManagementDetailInfo(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSurveyManagementDetailInfoQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
>;
export type GetSurveyManagementDetailInfoQueryError = Blob;

export function useGetSurveyManagementDetailInfo<
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
					TError,
					Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementDetailInfo<
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
					TError,
					Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementDetailInfo<
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자가 응답을 확인할 설문을 상세 조회합니다.
 */

export function useGetSurveyManagementDetailInfo<
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetSurveyManagementDetailInfoQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetSurveyManagementDetailInfoSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetSurveyManagementDetailInfoQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
	> = ({ signal }) =>
		getSurveyManagementDetailInfo(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSurveyManagementDetailInfoSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>
>;
export type GetSurveyManagementDetailInfoSuspenseQueryError = Blob;

export function useGetSurveyManagementDetailInfoSuspense<
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementDetailInfoSuspense<
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSurveyManagementDetailInfoSuspense<
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자가 응답을 확인할 설문을 상세 조회합니다.
 */

export function useGetSurveyManagementDetailInfoSuspense<
	TData = Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
	TError = Blob,
>(
	params: GetSurveyManagementDetailInfoParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getSurveyManagementDetailInfo>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetSurveyManagementDetailInfoSuspenseQueryOptions(
		params,
		options,
	);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
