/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";

import { apiClient } from "../axios/orvalMutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getThrowErrorUrl = () => {
	return `/sentry-test/throw`;
};

export const throwError = async (options?: RequestInit): Promise<Blob> => {
	return apiClient<Blob>(getThrowErrorUrl(), {
		...options,
		method: "GET",
	});
};

export const getThrowErrorInfiniteQueryKey = () => {
	return ["infinite", `/sentry-test/throw`] as const;
};

export const getThrowErrorQueryKey = () => {
	return [`/sentry-test/throw`] as const;
};

export const getThrowErrorInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof throwError>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof throwError>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getThrowErrorInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof throwError>>> = ({
		signal,
	}) => throwError({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof throwError>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ThrowErrorInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof throwError>>
>;
export type ThrowErrorInfiniteQueryError = Blob;

export function useThrowErrorInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof throwError>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof throwError>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof throwError>>,
					TError,
					Awaited<ReturnType<typeof throwError>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useThrowErrorInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof throwError>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof throwError>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof throwError>>,
					TError,
					Awaited<ReturnType<typeof throwError>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useThrowErrorInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof throwError>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof throwError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useThrowErrorInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof throwError>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof throwError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getThrowErrorInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getThrowErrorQueryOptions = <
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof throwError>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getThrowErrorQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof throwError>>> = ({
		signal,
	}) => throwError({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof throwError>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ThrowErrorQueryResult = NonNullable<
	Awaited<ReturnType<typeof throwError>>
>;
export type ThrowErrorQueryError = Blob;

export function useThrowError<
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof throwError>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof throwError>>,
					TError,
					Awaited<ReturnType<typeof throwError>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useThrowError<
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof throwError>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof throwError>>,
					TError,
					Awaited<ReturnType<typeof throwError>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useThrowError<
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof throwError>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useThrowError<
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof throwError>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getThrowErrorQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getThrowErrorSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof throwError>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getThrowErrorQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof throwError>>> = ({
		signal,
	}) => throwError({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof throwError>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ThrowErrorSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof throwError>>
>;
export type ThrowErrorSuspenseQueryError = Blob;

export function useThrowErrorSuspense<
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof throwError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useThrowErrorSuspense<
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof throwError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useThrowErrorSuspense<
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof throwError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useThrowErrorSuspense<
	TData = Awaited<ReturnType<typeof throwError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof throwError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getThrowErrorSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getCaptureErrorUrl = () => {
	return `/sentry-test/capture`;
};

export const captureError = async (options?: RequestInit): Promise<Blob> => {
	return apiClient<Blob>(getCaptureErrorUrl(), {
		...options,
		method: "GET",
	});
};

export const getCaptureErrorInfiniteQueryKey = () => {
	return ["infinite", `/sentry-test/capture`] as const;
};

export const getCaptureErrorQueryKey = () => {
	return [`/sentry-test/capture`] as const;
};

export const getCaptureErrorInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof captureError>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof captureError>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCaptureErrorInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof captureError>>> = ({
		signal,
	}) => captureError({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof captureError>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CaptureErrorInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof captureError>>
>;
export type CaptureErrorInfiniteQueryError = Blob;

export function useCaptureErrorInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof captureError>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof captureError>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof captureError>>,
					TError,
					Awaited<ReturnType<typeof captureError>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCaptureErrorInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof captureError>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof captureError>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof captureError>>,
					TError,
					Awaited<ReturnType<typeof captureError>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCaptureErrorInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof captureError>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof captureError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCaptureErrorInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof captureError>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof captureError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getCaptureErrorInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getCaptureErrorQueryOptions = <
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof captureError>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCaptureErrorQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof captureError>>> = ({
		signal,
	}) => captureError({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof captureError>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CaptureErrorQueryResult = NonNullable<
	Awaited<ReturnType<typeof captureError>>
>;
export type CaptureErrorQueryError = Blob;

export function useCaptureError<
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof captureError>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof captureError>>,
					TError,
					Awaited<ReturnType<typeof captureError>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCaptureError<
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof captureError>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof captureError>>,
					TError,
					Awaited<ReturnType<typeof captureError>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCaptureError<
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof captureError>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCaptureError<
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof captureError>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getCaptureErrorQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getCaptureErrorSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof captureError>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCaptureErrorQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof captureError>>> = ({
		signal,
	}) => captureError({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof captureError>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CaptureErrorSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof captureError>>
>;
export type CaptureErrorSuspenseQueryError = Blob;

export function useCaptureErrorSuspense<
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof captureError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCaptureErrorSuspense<
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof captureError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCaptureErrorSuspense<
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof captureError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCaptureErrorSuspense<
	TData = Awaited<ReturnType<typeof captureError>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof captureError>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getCaptureErrorSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
