/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OnSurvey API Docs
 * OnSurvey Spring boot Api Document 입니다.
 * OpenAPI spec version: 0.0.1
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useInfiniteQuery,
	useMutation,
	useQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";
import { apiClient } from "../axios/orvalMutator";
import type { IapGrantRequest } from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 주문 상태 재검증
 * @summary IAP 주문 상태 조회
 */
export const getStatusUrl = () => {
	return `/toss/iap/status`;
};

export const status = async (
	iapGrantRequest: IapGrantRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getStatusUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(iapGrantRequest),
	});
};

export const getStatusMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof status>>,
		TError,
		{ data: IapGrantRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof status>>,
	TError,
	{ data: IapGrantRequest },
	TContext
> => {
	const mutationKey = ["status"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof status>>,
		{ data: IapGrantRequest }
	> = (props) => {
		const { data } = props ?? {};

		return status(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type StatusMutationResult = NonNullable<
	Awaited<ReturnType<typeof status>>
>;
export type StatusMutationBody = IapGrantRequest;
export type StatusMutationError = Blob;

/**
 * @summary IAP 주문 상태 조회
 */
export const useStatus = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof status>>,
			TError,
			{ data: IapGrantRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof status>>,
	TError,
	{ data: IapGrantRequest },
	TContext
> => {
	return useMutation(getStatusMutationOptions(options), queryClient);
};
/**
 * orderId 서버검증 후 우리 도메인(PAYMENT)에 결제 반영. 멱등 처리됨.
 * @summary IAP 상품 지급(결제 반영)
 */
export const getGrantUrl = () => {
	return `/toss/iap/grant`;
};

export const grant = async (
	iapGrantRequest: IapGrantRequest,
	options?: RequestInit,
): Promise<Blob> => {
	return apiClient<Blob>(getGrantUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(iapGrantRequest),
	});
};

export const getGrantMutationOptions = <
	TError = Blob,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof grant>>,
		TError,
		{ data: IapGrantRequest },
		TContext
	>;
	request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof grant>>,
	TError,
	{ data: IapGrantRequest },
	TContext
> => {
	const mutationKey = ["grant"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof grant>>,
		{ data: IapGrantRequest }
	> = (props) => {
		const { data } = props ?? {};

		return grant(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GrantMutationResult = NonNullable<
	Awaited<ReturnType<typeof grant>>
>;
export type GrantMutationBody = IapGrantRequest;
export type GrantMutationError = Blob;

/**
 * @summary IAP 상품 지급(결제 반영)
 */
export const useGrant = <TError = Blob, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof grant>>,
			TError,
			{ data: IapGrantRequest },
			TContext
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof grant>>,
	TError,
	{ data: IapGrantRequest },
	TContext
> => {
	return useMutation(getGrantMutationOptions(options), queryClient);
};
/**
 * 현재 로그인 유저의 IAP 결제 총 횟수/총 금액(성공 결제 기준)
 * @summary 내 IAP 결제 통계
 */
export const getStatsUrl = () => {
	return `/toss/iap/stats`;
};

export const stats = async (options?: RequestInit): Promise<Blob> => {
	return apiClient<Blob>(getStatsUrl(), {
		...options,
		method: "GET",
	});
};

export const getStatsInfiniteQueryKey = () => {
	return ["infinite", `/toss/iap/stats`] as const;
};

export const getStatsQueryKey = () => {
	return [`/toss/iap/stats`] as const;
};

export const getStatsInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof stats>>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getStatsInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof stats>>> = ({
		signal,
	}) => stats({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof stats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StatsInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof stats>>
>;
export type StatsInfiniteQueryError = Blob;

export function useStatsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof stats>>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof stats>>,
					TError,
					Awaited<ReturnType<typeof stats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStatsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof stats>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof stats>>,
					TError,
					Awaited<ReturnType<typeof stats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStatsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof stats>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 IAP 결제 통계
 */

export function useStatsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof stats>>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getStatsInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getStatsQueryOptions = <
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getStatsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof stats>>> = ({
		signal,
	}) => stats({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof stats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StatsQueryResult = NonNullable<Awaited<ReturnType<typeof stats>>>;
export type StatsQueryError = Blob;

export function useStats<
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof stats>>,
					TError,
					Awaited<ReturnType<typeof stats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStats<
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof stats>>,
					TError,
					Awaited<ReturnType<typeof stats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStats<
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 IAP 결제 통계
 */

export function useStats<
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getStatsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const getStatsSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
	>;
	request?: SecondParameter<typeof apiClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getStatsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof stats>>> = ({
		signal,
	}) => stats({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof stats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StatsSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof stats>>
>;
export type StatsSuspenseQueryError = Blob;

export function useStatsSuspense<
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStatsSuspense<
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStatsSuspense<
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 IAP 결제 통계
 */

export function useStatsSuspense<
	TData = Awaited<ReturnType<typeof stats>>,
	TError = Blob,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<Awaited<ReturnType<typeof stats>>, TError, TData>
		>;
		request?: SecondParameter<typeof apiClient>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getStatsSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return { ...query, queryKey: queryOptions.queryKey };
}
